routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('index');});
Route::get('/index', function () { return view('index');});

Route::get('/required-proofs', function () { return view('pages.required-proofs');});
Route::get('/faq', function () { return view('pages.faq');});
Route::get('/contact', function () { return view('pages.contact');});
Route::get('/terms-and-conditions', function () { return view('pages.terms-and-conditions');});
Route::get('/privacy-policy', function () { return view('pages.privacy-policy');});
Route::get('/refund-policy', function () { return view('pages.refund-policy');});
Route::get('/disclaimer', function () { return view('pages.disclaimer');});
Route::get('/about', function () { return view('pages.about');});
Route::get('/makepayment', function () { return view('pages.makepayment');});	

Route::post('/update', 'DataController@store')->name('update');
Route::get('/chirag', 'PanController@chirag');

Route::get('/makepayment/{pan_id}', 'DataController@makepayment')->name('makepayment');

Route::post('/createorder', 'DataController@createOrder')->name('update');
Route::post('/updatetransaction', 'DataController@updateTransaction');

app/Transactions.php
<?php

namespace App;

use Carbon\Carbon;
use Exception;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Log;
use Illuminate\Database\Eloquent\Model;

class Transactions extends Model
{
    protected $table = "tbl_transactions";
    public $incrementing = false;
    public $timestamps = false;
    public $timezone = 'Asia/Kolkata';

    public function addTransaction($pan_id, $order_id, $first_name, $email, $mobile_number) {
        try {
            

            $transaction = $this;
            $transaction->pan_id = $pan_id;
            $transaction->order_id = $order_id;
            $transaction->first_name = $first_name;
            $transaction->email = $email;
            $transaction->mobile_number = $mobile_number;
            

            if ($transaction->save()) {
                return $transaction;
            }

            return false;
        } catch (QueryException $ex) {
            Log::error('Error while executing SQL Query', [
                'class' => 'Transactions',
                'function' => 'addTransaction',            
                'line_no' => $ex->getLine(),
                'error_message' => $ex->getMessage(),
            ]);

            return false;
        } catch (Exception $ex) {
            Log::error('Error while executing SQL Query', [
                'class' => 'Transactions',
                'function' => 'addTransaction',        
                'line_no' => $ex->getLine(),
                'error_message' => $ex->getMessage(),
            ]);

            return false;
        }
    }

    public function updateTransaction($payment) {
        try {
            
            $order_id = $payment['order_id'];
            
            $this->where('order_id', $order_id)->update([
                'payment_id' => $payment['id'],
                'status' => $payment['status'],
                'amount' => $payment['amount']/100,
                'method' => $payment['method'],
            ]);
                    
            return $order_id;
        } catch (QueryException $ex) {
            Log::error('Error while executing SQL Query', [
                'class' => 'Transactions',
                'function' => 'addTransaction',                
                'line_no' => $ex->getLine(),
                'error_message' => $ex->getMessage(),
            ]);

            return false;
        } catch (Exception $ex) {
            Log::error('Error while executing SQL Query', [
                'class' => 'Transactions',
                'function' => 'addTransaction',            
                'line_no' => $ex->getLine(),
                'error_message' => $ex->getMessage(),
            ]);

            return false;
        }
    }
    protected $fillable = [];


    protected $hidden = [];

    protected $casts = [];

    public function getTimestampAttribute($value)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $value, $this->timezone)->format('d/m/Y h:i:s A');
    }
}

resources/views/pages/about.blade.php
@include('include.head')

<body>
	<div class="header" id="">
		@include('include.header')
	</div>
	<div id="main-content">
		<div id="order-form-thank-you" class="container-fluid p-20px mt-20px">
			<div class="container">
				<div class="col-md-12 text-center text-blue bg-white p-40px box-shadow">
					<div class="col-md-12 text-center">
						<label class="control-form-label text-orange fw-700 fs-24 pt-0">ABOUT US</label>
						<hr>
						<br>
						<p class="uppercase">https://onlinepanseva.in/ a technology based global platform is founded by group of professionals holding expertise in taxation, laws and related consultation on Government Documents. We have introduced https://onlinepanseva.in/ with the aim of serving our clients with best and reliable online assistance and advisory to help Entrepreneurs in setting up and running their business.</p>
						<p class="uppercase">Our goal is to apply strategic thinking, dedicated support, complete efforts and practical approach in order to provide quick, hassle free and automated professional services to our clients.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	@include('include.footer')

resources/views/pages/contact.blade.php
@include('include.head')

<body>
	<div class="header" id="">
		<@include('include.header')
	</div>
	<div id="main-content">
		<div id="order-form-thank-you" class="container-fluid p-20px mt-20px">
			<div class="container">
				<div class="col-md-12 text-center text-blue bg-white p-40px box-shadow">
					<div class="col-md-12 text-center">
						<label class="control-form-label text-orange fw-700 fs-24 pt-0">Contact US</label>
						<hr>
						<br>
						<p>Email ID: <b><a class="text-orange td-none" href="">connect.panseva@gmail.com</span></a></b>					
						</p>
						<p>Mo. Number: <b><a class="text-orange td-none" href="">+91 7435 803 802</span></a></b>					
						</p>
						<p>We are complying with the government regulations due to Covid-19. Our support teams are overwhelmed due to the high volumes of Application our executive contact you within 48Hour </p>
						<p class="text-orange">Support hours: Mon-Fri 10AM-6PM</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	@include('include.footer')

resources/views/pages/disclaimer.blade.php
@include('include.head')

<body>
	<div class="header" id="header">
		@include('include.header')
	</div>
	<div id="main-content">
		<div id="order-form-thank-you" class="container-fluid p-20px mt-20px">
			<div class="container">
				<div class="col-md-12 text-center text-blue bg-white p-40px box-shadow">
					<div class="col-md-12 text-center">
						<label class="control-form-label text-orange fw-700 fs-24 pt-0">DISCLAIMER POLICY</label>
						<hr>
						<br>
						<p class="text-justify">PLEASE READ THIS DOCUMENT CAREFULLY BEFORE ACCESSING OR USING THE SITE. BY ACCESSING OR USING THE SITE, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS SET FORTH BELOW. IF YOU DO NOT WISH TO BE BOUND BY THESE TERMS AND CONDITIONS, YOU MAY NOT ACCESS OR USE THE SITE. https://onlinepanseva.in/ MAY MODIFY THIS AGREEMENT AT ANY TIME, AND SUCH MODIFICATIONS SHALL BE EFFECTIVE IMMEDIATELY UPON POSTING OF THE MODIFIED AGREEMENT ON THE SITE. YOU AGREE TO REVIEW THE AGREEMENT PERIODICALLY TO BE AWARE OF SUCH MODIFICATIONS AND YOUR CONTINUED ACCESS OR USE OF THE SITE SHALL BE DEEMED YOUR CONCLUSIVE ACCEPTANCE OF THE MODIFIED AGREEMENT.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>1. USE OF THE SITE</b>
						</label>
						<hr class="hr">
						<p class="text-justify mt-20px">YOU UNDERSTAND THAT, EXCEPT FOR INFORMATION, PRODUCTS OR SERVICES CLEARLY IDENTIFIED AS BEING SUPPLIED BY https://onlinepanseva.in/, WE DOES NOT OPERATE, CONTROL OR ENDORSE ANY INFORMATION, PRODUCTS OR SERVICES ON THE INTERNET IN ANY WAY.</p>
						<p class="text-justify">YOU ALSO UNDERSTAND THAT https://onlinepanseva.in/ CANNOT AND DOES NOT GUARANTEE OR WARRANT THAT FILES AVAILABLE FOR DOWNLOADING THROUGH THE SITE WILL BE FREE OF INFECTION OR VIRUSES, WORMS, TROJAN HORSES OR OTHER CODE THAT MANIFEST CONTAMINATING OR DESTRUCTIVE PROPERTIES. YOU ARE RESPONSIBLE FOR IMPLEMENTING SUFFICIENT PROCEDURES AND CHECKPOINTS TO SATISFY YOUR PARTICULAR REQUIREMENTS FOR ACCURACY OF DATA INPUT AND OUTPUT, AND FOR MAINTAINING A MEANS EXTERNAL TO THE SITE FOR THE RECONSTRUCTION OF ANY LOST DATA.</p>
						<p class="text-justify">YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SITE AND THE INTERNET. https://onlinepanseva.in/ PROVIDES THE SITE AND RELATED INFORMATION "AS IS" AND DOES NOT MAKE ANY EXPRESS OR IMPLIED WARRANTIES, REPRESENTATIONS OR ENDORSEMENTS WHATSOEVER (INCLUDING WITHOUT LIMITATION WARRANTIES OF TITLE OR NONINFRINGEMENT, OR THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE) WITH REGARD TO THE SERVICE, ANY MERCHANDISE INFORMATION OR SERVICE PROVIDED THROUGH THE SERVICE OR ON THE INTERNET GENERALLY, AND https://onlinepanseva.in/ SHALL NOT BE LIABLE FOR ANY COST OR DAMAGE ARISING EITHER DIRECTLY OR INDIRECTLY FROM ANY SUCH TRANSACTION. IT IS SOLELY YOUR RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS AND USEFULNESS OF ALL OPINIONS, ADVICE, SERVICES, MERCHANDISE AND OTHER INFORMATION PROVIDED THROUGH THE SERVICE OR ON THE INTERNET GENERALLY. https://onlinepanseva.in/ DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE OR THAT DEFECTS IN THE SERVICE WILL BE CORRECTED. YOU UNDERSTAND FURTHER THAT THE PURE NATURE OF THE INTERNET CONTAINS UNEDITED MATERIALS SOME OF WHICH ARE SEXUALLY EXPLICIT OR MAY BE OFFENSIVE TO YOU. YOUR ACCESS TO SUCH MATERIALS IS AT YOUR RISK. https://onlinepanseva.in/ HAS NO CONTROL OVER AND ACCEPTS NO RESPONSIBILITY WHATSOEVER FOR SUCH MATERIALS.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>2. LIMITATION OF LIABILITY</b>
						</label>
						<hr class="hr">
						<p class="text-justify mt-20px">IN NO EVENT WILL https://onlinepanseva.in/ BE LIABLE FOR (I) ANY INCIDENTAL, CONSEQUENTIAL, OR INDIRECT DAMAGES (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, BUSINESS INTERRUPTION, LOSS OF PROGRAMS OR INFORMATION, AND THE LIKE) ARISING OUT OF THE USE OF OR INABILITY TO USE THE SERVICE, OR ANY INFORMATION, OR TRANSACTIONS PROVIDED ON THE SERVICE, OR DOWNLOADED FROM THE SERVICE, OR ANY DELAY OF SUCH INFORMATION OR SERVICE. EVEN IF https://onlinepanseva.in/ OR ITS AUTHORIZED REPRESENTATIVES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR (II) ANY CLAIM ATTRIBUTABLE TO ERRORS, OMISSIONS, OR OTHER INACCURACIES IN THE SERVICE AND/OR MATERIALS OR INFORMATION DOWNLOADED THROUGH THE SERVICE. BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES, https://onlinepanseva.in/ LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>3. INDEMNIFICATION</b>
						</label>
						<hr class="hr">
						<p class="text-justify mt-20px">YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS https://onlinepanseva.in/, ITS OFFICERS, EMPLOYEES AND ANY THIRD PARTY INFORMATION PROVIDERS TO THE SERVICE FROM AND AGAINST ALL LOSSES, EXPENSES, DAMAGES AND COSTS, INCLUDING REASONABLE ATTORNEYS' FEES, RESULTING FROM ANY VIOLATION OF THIS AGREEMENT (INCLUDING NEGLIGENT OR WRONGFUL CONDUCT) BY YOU OR ANY OTHER PERSON ACCESSING THE SERVICE.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>4. MISCELLANEOUS</b>
						</label>
						<hr class="hr">
						<p class="text-justify mt-20px">THIS AGREEMENT SHALL ALL BE GOVERNED AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF INDIA APPLICABLE TO AGREEMENTS MADE AND TO BE PERFORMED IN INDIA. YOU AGREE THAT ANY LEGAL ACTION OR PROCEEDING BETWEEN https://onlinepanseva.in/ AND YOU FOR ANY PURPOSE CONCERNING THIS AGREEMENT OR THE PARTIES' OBLIGATIONS HEREUNDER SHALL BE BROUGHT EXCLUSIVELY IN A FEDERAL OR STATE COURT OF COMPETENT JURISDICTION SITTING IN INDIA. ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE WITH RESPECT TO THE SERVICE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CLAIM OR CAUSE OF ACTION ARISES OR SUCH CLAIM OR CAUSE OF ACTION IS BARRED.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
@include('include.footer')

resources/views/pages/makepayment.blade.php
 @include('include.head')
    <body onload="">
        <div class="header" id="header">
            <div class="container-fluid mb-10px">
                <div class="row text-center">
                    <div class="col">
                        <a href="/"><img class="header-left-image" src="{{ asset('assets/img/online-msme-logo.png') }}" /></a>
                    </div>
                    <div class="col">
                        <img class="header-center-image mt-20px" src="{{ asset('assets/img/online-msme-center-image.png') }}" />
                    </div>
                    <div class="col d-none d-md-block">
                        <img class="header-right-image" src="{{ asset('assets/img/shopact-msme-gst-swacha-bharat.png') }}" />
                    </div>
                </div>
            </div>
            <nav class="navbar navbar-light bg-light-gray">
               
                <div class="navbar-collapse justify-content-md-center collapse" style="">
                    <ul class="navbar-nav">
                    
                    </ul>
                </div>
            </nav>
        </div>
        <div id="main-content">
            <div class="container ptb-1rem">
                <div class="row justify-content-center">
                    <div class="col-sm-8 mt-5px text-center">
                        <label class="control-form-label text-orange fw-700 fs-24 pt-0"></label>
                    </div>
                </div>
            </div>
            @if (Session::has('message'))
               <div class="alert alert-success" role="alert">
                   {{Session::get('message')}}
               </div>
            @endif
            <div class="container">
                <div class="">
                    <div class="col-md-12 text-center">
                        <label class="control-form-label text-orange fw-700 fs-24 pt-0">Application No: {{ $info->pan_id }}</label>
                    </div>
                    <div class="col-md-12 col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-bordered" style="text-align: start;">
                                <tbody>
                                     
                                <tr>
                                  <td><b>Applicant Name:-</b> {{ $info->applicant_first_name }} {{ $info->applicant_middle_name }} {{ $info->applicant_last_name }}</td>
                                  
                                </tr>
                               
                                <tr>
                                  <td><b>Email ID:-</b>  {{ $info->applicant_email_id }}</td>
                                 
                                </tr>
                               
                                <tr>
                                  <td><b>Apply Date:-</b> {{ $info->timestamp }}</td>
                                  
                                </tr>
                                
                              </tbody>
                            </table>
                        </div>
                              
                            <div class="" style="text-align: center; margin-top: 20px; margin-bottom:20px;">
                                <button class="btn btn-primary" id="pay">Pay Securely</button>
                               
                            </div>
                            <!-- <div class="" style="text-align: center; margin-top: 20px; margin-bottom:20px;">
                                
                                <a href="https://paytm.me/Fl-heKB"><button class="btn btn-primary">Pay With Paytm</button></a>
                            </div> -->
                            
                            <div class="row">
                                <div class="col-md-4 col-xs-12">
                                    <div class="agree-img" class="img-responsive" >
                                        <img src="https://pass-india.org/img/payment-logos.png" class="img-responsive" style="width: 324px;">
                                    </div><!-- <br>
                                    <H5>Benefits of Having a Pan Application </H5>
                                    <p>- Identity Proof </p>
                                    <p>- Opening a Bank Account</p>
                                    <p>- IT Returns Filing</p>
                                    <p>- Starting a Business</p>
                                    <p>- Tax Deductions</p>
                                    <p>- Time Deposit</p>
                                    <p>- Purchase or Sale of Goods and Services</p>
                                    <p>- Foreign Travel</p>
                                </div> -->
                                
                            </div>
                            
                    </div>
                    <br>
                    <div class="col-md-12 text-center">
                        <label class="control-form-label text-orange fw-700 fs-24 pt-0">Contact US</label>
                        <hr>
                        <br>
                        <p>Email ID: <b><a class="text-orange td-none" href="">connect.panseva@gmail.com</span></a></b>                  
                        </p>
                        <p>Mo. Number: <b><a class="text-orange td-none" href="">+91 7435 803 802</span></a></b>                    
                        </p> 
                        <p>We are complying with the government regulations due to Covid-19. Our support teams are overwhelmed due to the high volumes of Application our executive contact you within 48Hour </p>               
                        


                        
                    </div>
                </div>    
            </div>
        </div>

<script type="application/javascript" crossorigin="anonymous" src="https://securegw.paytm.in/merchantpgpui/checkoutjs/merchants/vknUlk68127034744655.js" 
                onload="onScriptLoad();"></script>
        <script>
            function onScriptLoad(){
                var config = {
                 "root": "",
                 "flow": "DEFAULT",
                 "data": {
                  "orderId": "" /* update order id */,
                  "token": "" /* update token value */,
                  "tokenType": "TXN_TOKEN",
                  "amount": "" /* update amount */
                 },
                 "handler": {
                    "notifyMerchant": function(eventName,data){
                      console.log("notifyMerchant handler function called");
                      console.log("eventName => ",eventName);
                      console.log("data => ",data);
                    } 
                  }
                };

                if(window.Paytm && window.Paytm.CheckoutJS){
                    window.Paytm.CheckoutJS.onLoad(function excecuteAfterCompleteLoad() {
                        // initialze configuration using init method 
                        window.Paytm.CheckoutJS.init(config).then(function onSuccess() {
                           // after successfully update configuration invoke checkoutjs
                           window.Paytm.CheckoutJS.invoke();
                        }).catch(function onError(error){
                            console.log("error => ",error);
                        });
                    });
                } 
            }
            var rzp1 = (onScriptLoad);
            document.getElementById('paytm').onclick = function(e){
                rzp1.open();
                e.preventDefault();
            }
        </script>

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>

    
 var name = <?php echo json_encode( $result->first_name) ?>;
 var email = <?php echo json_encode( $result->email) ?>;
 var contact = <?php echo json_encode( $result->mobile_number) ?>;
 var order_id = <?php echo json_encode( $result->order_id) ?>;

var options = {
    "key": "rzp_live_MHIB7VJ4qhRsWM", //rzp_test_7fj4d4ByPL0wzy Enter the Key ID generated from the Dashboard
    "amount": "10700", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "title": "Online Pan Seva",
    "description": "Pan Card Fees",
    "image": "https://www.onlinepanseva.in/assets/img/favicon.ico",
    "order_id": order_id, //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "https://www.onlinepanseva.in/updatetransaction",
    /*"handler": function (response){
            
            alert(response.razorpay_payment_id);
            alert(response.razorpay_order_id);
            alert(response.razorpay_signature)
            alert('Your Payment successfully');
            
            //window.location.href = "http://onlinepanseva.in";
    },*/
    "prefill": {
        "name": 'name',
        "email": email,
        "contact": contact
    },
};
var rzp1 = new Razorpay(options);
document.getElementById('pay').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}

</script>  
        
        @include('include.footer')

resources/views/pages/refund-policy.blade.php
@include('include.head')
<body>
	<div class="header" id="header">
		@include('include.head')
	</div>
	<div id="main-content">
		<div id="order-form-thank-you" class="container-fluid p-20px mt-20px">
			<div class="container">
				<div class="col-md-12 text-center text-blue bg-white p-40px box-shadow">
					<div class="col-md-12 text-center">
						<label class="control-form-label text-orange fw-700 fs-24 pt-0">REFUND POLICY</label>
						<hr>
						<br>
						<label class="control-form-label text-blue pt-0"><b>1. REFUND OF PAYMENT RECEIVED</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">For the PAN Services that are given to you, https://onlinepanseva.in/, will only accept refunds if the service is not provided. https://onlinepanseva.in/, reserves the right to determine a fair value of the product on return and the same shall be binding on both parties. The refund process will be initiated once we confirmation of the services not provided. In case of refund request accepted, amount WILL BE REFUNDED IN THE SAME MODE YOU HAVE PAID. ALSO IF THERE IS DELAY BEYOND 45 DAYS FOR SUBMITTING HARD COPY OF FORM, NO REFUND SHALL BE MADE AGAINST SUCH TRANSACTION.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>2. REFUND REQUEST</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">REFUND REQUEST CAN BE SEND AT <a href="cdn-cgi/l/email-protection.html" class="__cf_email__" data-cfemail="20434f4e544143540e50414e494e4460474d41494c0e434f4d0e">[email&#160;protected]</a> REFUND REQUEST CAN BE MADE WITHIN 10 DAYS OF ONLINE APPLICATION MADE.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>3. CANCELLATION OF APPLICATION</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">YOU CANNOT CANCEL THE APPLICATION ONCE PROCESSED FROM OUR SIDE. NO REFUND WILL BE PROVIDED ONCE THE APPLICATION IS DONE.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>4. ISSUANCE OF PAN CARD</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">PANCARD APPLIED, WILL BE DELIVERED WITHIN 30 TO 45 DAYS (AFTER RECEIPT OF HARD COPY APPLICATION) OF AT THE ADDRESS PROVIDED IN THE APPLICATION FORM.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>5. REFUND ANY CASE</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">if in any case you want to get a refund after completing payment, then we will debited processing charges, GST charges, and payment gateway charges.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>6. FORCE MAJEURE</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">https://onlinepanseva.in/ SHALL NOT BE CONSIDERED IN BREACH OF ITS SATISFACTION GUARANTEE POLICY OR DEFAULT UNDER ANY TERMS OF SERVICE, AND SHALL NOT BE LIABLE TO THE CLIENT FOR ANY CESSATION, INTERRUPTION, OR DELAY IN THE PERFORMANCE OF ITS OBLIGATIONS BY REASON OF EARTHQUAKE, FLOOD, FIRE, STORM, LIGHTNING, DROUGHT, LANDSLIDE, HURRICANE, CYCLONE, TYPHOON, TORNADO, NATURAL DISASTER, ACT OF GOD OR THE PUBLIC ENEMY, EPIDEMIC, FAMINE OR PLAGUE, ACTION OF A COURT OR PUBLIC AUTHORITY, CHANGE IN LAW, EXPLOSION, WAR, TERRORISM, ARMED CONFLICT, LABOR STRIKE, LOCKOUT, BOYCOTT OR SIMILAR EVENT BEYOND OUR REASONABLE CONTROL, WHETHER FORESEEN OR UNFORESEEN (EACH A "FORCE MAJEURE EVENT").</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>7. REFUND REQUEST</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">REFUND REQUEST CAN BE SEND AT <a href="cdn-cgi/l/email-protection.html" class="__cf_email__" data-cfemail="86e5e9e8f2e7e5f2a8f6e7e8efe8e2c6e1ebe7efeaa8e5e9eba8">[email&#160;protected]</a> REFUND REQUEST CAN BE COMPLETE WITHIN 5 DAYS OF ONLINE APPLICATION MADE WITH VALID REASON. STANDARD DEDUCTION SHOULD BE APPLIED IF YOU DONT HAVE VALID REASON.</p>
						<br>
						<label class="control-form-label text-blue pt-0"><b>8. CLARIFICATION ABOUT APPLICATION</b>
						</label>
						<hr class="hr">
						<p class="text-justify uppercase mt-20px">IF YOU HAVE ANY QUERY ABOUT APPLICATION PROCESS, YOU CAN WRITE US MAIL <a href="cdn-cgi/l/email-protection.html" class="__cf_email__" data-cfemail="a2c1cdccd6c3c1d68cd2c3cccbccc6e2c5cfc3cbce8cc1cdcf8c">[email&#160;protected]</a> IN CASE WE NEED ANY ADDITIONAL CLARIFICATION ABOUT YOUR PAN APPLICATION, OUR TEAM WILL REACH YOU BY EMAIL OR CALL.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
@include('include.footer')